name: Greetings

on:
  schedule: 
    - cron: "* * * * *"

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
