name: Greetings

on:
  schedule: 
    - cron: "* * * * *"

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello'
        name: HelloTestEcho      
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
        name: TestCI
